config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :order_articles

  resources :items
  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item

  # def unit_price
  #   item.price
  # end

  def quantity
    quantity = 0
    quantity +=1
    quantity
  end

  def sub_total
    order.collect{|order| order.valid? ? order.item.price * order.quantity : 0}.sum
  end

  def shipping
    if sub_total > 20.00
      0
    else
      5.00
    end
  end

  def total
    sub_total + shipping
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :nullify
  has_many :items, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    def index
      @items = Item.all
    end

    def show
    end

    def new
      @item = Item.new
      @current_user = current_user
    end

    def edit
    end

    def create
      @item = Item.new(item_params)

      respond_to do |format|
        if @item.save
          redirect_to items_path(@user), notice: 'Item was successfully created.'
        else
           render :new, status: :unprocessable_entity
        end
      end
    end

    def destroy
      @item.destroy
      redirect_to items_path(@user), status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_item
        @item = Item.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def item_params
        params.require(:item).permit(:description, :price)
      end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @order.user = current_user
  end

  def create
    @order = current_order
    @item = Item.find(params[:item_id])
    @order = Order.new(order_params)
    @order.user = current_user
    @order.item = @item
    if @order.save
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :item_id, :sub_total, :shipping, :quantity, :total)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container">
    <% @articles.each do |article| %>

        <%# <div class="card"> %>
                <h3><div><%= article.article_description %></div></h3>
                <h3><div>Price <%= article.price %></div></h3>
                <%# set up enum later...do NOT forget! %>
                 <h3><div><%#= article.availability %></div></h3>
                <h3>Stock <div><%= article.stock_qty %></div></h3>
               <div><%= link_to " Add to cart", article_path(article)%></div>
          <%# </div> %>

    <% end %>
  </div>

<br>

<div class="back_main">
  <%=  link_to "Back to Main Page", root_path%>
</div>

app/views/items/index.html.erb
<div class="container">
    <% @items.each do |item| %>

        <%# <div class="card"> %>
                <h3><div><%= item.description %></div></h3>
                <h3><div>Price <%= item.price %></div></h3>
                <%# set up enum later...do NOT forget! %>
                 <h3><div><%#= article.availability %></div></h3>
               <div><%= link_to " Add to cart", new_order_path(@order)%></div>
          <%# </div> %>

    <% end %>
  </div>

<br>

<div class="back_main">
  <%=  link_to "Back to Main Page", root_path%>
</div>

app/views/items/show.html.erb
<div><%= @item.description %></div>
<div><%= @item.price %></div>

<div><%= link_to "Order", order_path(orders)%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PintasPanama6</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<% @items.each do |product| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', order_path(items) %></td>



        <td>


          <%= form_for @order, remote: true  do |f|%>
          <%= f.hidden_field :item_id, :value => item.id %>
          <%= f.number_field :quantity, :value => 1, :min =>  1%>
          <%= f.submit "Add to Cart "%>


          <% end %>
        </td>

      </tr>
    <% end %>

app/views/orders/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Total:</strong>
  <%= item.total %>
</p>

<%= link_to 'Back', root_path %>

app/views/pages/home.html.erb
  <div class="pic">
    <%= image_tag("Webp.net-resizeimage.png") %>
  </div>

  <div class="slogan">
    <h1>La Mejor Cerveza de Panama...a un Click!</h1>
  </div>

<div class="items-link">
<% if user_signed_in?  %>
<%=  link_to "Items", items_path(@items)%>
<% end %>
</div>

<div class="sign-out-link">
<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "Color logo - no background.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>